### ISSUE TITLE
undefined method `progname=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by nengine** [topofocus/active-orient#4] opened 2015-12-31 21:13 UTC
I'm getting error messages like below when a new vertex of class AirPort is created.  As you see below I'm creating two vertices NY and LA.  I have noticed that first vertex would however created in the database, but after it throws an error, second vertex LA would not be created.  Any help is greatly appreciated.  

```
/home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/base.rb:51:in `initialize': undefined method `progname=' for nil:NilClass (NoMethodError)
	from /home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/rest.rb:661:in `new'
	from /home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/rest.rb:661:in `create_document'
	from /home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/rest.rb:805:in `update_or_create_documents'
	from /home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/rest.rb:785:in `create_or_update_document'
	from /home/nash/.rvm/gems/ruby-2.2.1@rails4.2/gems/active-orient-0.41/lib/model.rb:140:in `create'
	from flights.rb:16:in `<main>'
```

```ruby
require 'rubygems'
require 'bundler/setup'
require 'active-orient'

ActiveOrient::OrientDB.default_server= { user: 'xxx', password: '123' }
r = ActiveOrient::OrientDB.new  database: 'TravelEngine'

A = r.create_vertex_class 'AirPort'
NY = A.create id: "NY", name: "New York"
LA = A.create id: "LA", name: "Los Angeles"
```

**Comment by topofocus** [comment] 2016-01-02 09:42
Hi,

this error is caused by a missing Loggin-Facility.

Include 
 logger =  Logger.new '/dev/stdout'
 ActiveOrient::Model.logger =  logger
 ActiveOrient::OrientDB.logger =  logger

in your startup procedure. This can be done on class-level, eg. before initialising an OrientDB-Object.
It will be fixed in the gem soon.

thanks for reporting the error
... hartmut ...

**Comment by nengine** [comment] 2016-01-02 13:07
Ok Thanks alot.




Sent from Samsung tablet.


-------- Original message --------

**Comment by enricribas** [comment] 2016-01-02 18:30
I was seeing this as well. Should probably be in the README example code. 
Thanks.

**Comment by topofocus** [comment] 2016-01-02 18:48
Its fixed by moving from config/boot to lib/active-orient.
The gem is updated as well.

If no Logger is specified, anything goes to STDOUT

**Closed** 2016-05-30 05:40 UTC
